insert into public.foods (id, bn, en, category, kcal_per_unit, protein_g, carbs_g, fat_g, unit_en, unit_bn, gi) values
  ('rice', 'ভাত', 'Steamed rice', 'rice', 240, 4, 53, 0.5, 'plate', 'প্লেট', 'high'),
  ('khichuri-bhuna', 'খিচুড়ি — ভুনা', 'Khichuri, bhuna', 'rice', 310, 9, 48, 8, 'plate', 'প্লেট', 'high'),
  ('khichuri-thin', 'খিচুড়ি — পাতলা', 'Khichuri, thin', 'rice', 180, 6, 30, 4, 'bowl', 'বাটি', 'medium'),
  ('khichuri-hilsa', 'খিচুড়ি ও ইলিশ ভাজা', 'Khichuri with fried hilsa', 'rice', 520, 22, 52, 24, 'plate', 'প্লেট', 'high'),
  ('khichuri-egg', 'ডিম খিচুড়ি', 'Egg khichuri', 'rice', 365, 14, 46, 13, 'plate', 'প্লেট', 'high'),
  ('porota', 'পরোটা', 'Paratha', 'rice', 170, 3, 20, 8, 'piece', 'পিস', 'high'),
  ('dal-red', 'মসুর ডাল', 'Red lentil dal', 'dal', 130, 8, 18, 3, 'bowl', 'বাটি', 'low'),
  ('dal-mug', 'মুগ ডাল', 'Mung dal', 'dal', 145, 9, 20, 3, 'bowl', 'বাটি', 'low'),
  ('bhorta-alu', 'আলু ভর্তা', 'Potato bhorta', 'bhorta', 95, 2, 14, 4, 'tbsp', 'চামচ', 'medium'),
  ('bhorta-begun', 'বেগুন ভর্তা', 'Eggplant bhorta', 'bhorta', 70, 1, 8, 4, 'tbsp', 'চামচ', 'low'),
  ('hilsa-fried', 'ইলিশ মাছ ভাজা', 'Fried hilsa', 'fish', 210, 18, 2, 14, 'piece', 'টুকরা', 'low'),
  ('rui-curry', 'রুই মাছের ঝোল', 'Rui fish curry', 'fish', 150, 16, 4, 8, 'piece', 'টুকরা', 'low'),
  ('chicken-curry', 'মুরগির মাংস', 'Chicken curry', 'meat', 220, 20, 5, 13, 'piece', 'টুকরা', 'low'),
  ('beef-bhuna', 'গরুর মাংস ভুনা', 'Beef bhuna', 'meat', 260, 19, 4, 18, 'piece', 'টুকরা', 'low'),
  ('mixed-veg', 'সবজি ভাজি', 'Mixed vegetable fry', 'vegetables', 90, 2, 10, 5, 'bowl', 'বাটি', 'low'),
  ('shak', 'শাক ভাজি', 'Sauteed greens', 'vegetables', 60, 2, 6, 3, 'bowl', 'বাটি', 'low'),
  ('singara', 'সিঙাড়া', 'Singara', 'snacks', 180, 3, 20, 10, 'piece', 'পিস', 'high'),
  ('piyaju', 'পিয়াজু', 'Piyaju', 'snacks', 90, 3, 8, 5, 'piece', 'পিস', 'medium'),
  ('mishti-doi', 'মিষ্টি দই', 'Sweet yogurt', 'sweets', 155, 4, 24, 5, 'cup', 'কাপ', 'high'),
  ('roshogolla', 'রসগোল্লা', 'Roshogolla', 'sweets', 106, 2, 21, 1, 'piece', 'পিস', 'high'),
  ('tea-milk', 'চা — দুধ ও চিনি', 'Tea with milk & sugar', 'drinks', 70, 1, 12, 2, 'cup', 'কাপ', 'medium'),
  ('lassi', 'লাচ্ছি', 'Lassi', 'drinks', 180, 5, 26, 6, 'glass', 'গ্লাস', 'medium'),
  ('biscuit-pack', 'প্যাকেট বিস্কুট', 'Packet biscuits', 'packaged', 140, 2, 20, 6, 'pack', 'প্যাকেট', 'high'),
  ('chanachur', 'চানাচুর', 'Chanachur mix', 'packaged', 160, 4, 16, 9, 'cup', 'কাপ', 'medium')
on conflict (id) do update set
  bn = excluded.bn,
  en = excluded.en,
  category = excluded.category,
  kcal_per_unit = excluded.kcal_per_unit,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  unit_en = excluded.unit_en,
  unit_bn = excluded.unit_bn,
  gi = excluded.gi;
